<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <!-- مكتبة الواجهات العصرية -->
    <PackageReference Include="MaterialDesignThemes" Version="4.9.0" />
    <!-- مكتبة لتصدير البيانات إلى إكسل بسهولة لاحقاً -->
    <PackageReference Include="ClosedXML" Version="0.102.1" />
  </ItemGroup>

</Project>
